apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.ms.name }}
  labels:
    app: {{ .Values.app.ms.name }}
    chart: {{ include "weather-chart.chart" . }}
    release: {{ .Values.app.ms.name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "weather-chart.name" . }}
    release: {{ .Values.app.ms.name }}
